### ISSUE TITLE
Assign human readable font-weights to names matching the spec

### ISSUE THREAD

**Issue by kaelig** [guardian/guss-webfonts#16]
When I built the list of human readable font-weights I wanted to match names given by Adobe and from other examples such as Wikipedia. But I just discovered the spec hints at certain names, and it might be a good idea to closely match the spec.

See http://www.w3.org/TR/css3-fonts/#font-weight-prop
- 100 - Thin
- 200 - Extra Light (Ultra Light)
- 300 - Light
- 400 - Normal
- 500 - Medium
- 600 - Semi Bold (Demi Bold)
- 700 - Bold
- 800 - Extra Bold (Ultra Bold)
- 900 - Black (Heavy)

Which would give us:

``` scss
// src/_webfonts.config.scss
/**
 * Human-readable Font-weights
 *
 * @type Map
 *
 * @group webfonts
 */
$guss-font-weights: (
    'thin':       100,
    'extralight': 200,
    'light':      300,
    'normal':     400,
    'medium':     500,
    'semibold':   600,
    'bold':       700,
    'extrabold':  800,
    'black':      900
) !default;
```

And then we just have to replace 'normal' weight with 'Regular' when composing filenames:

``` scss
// src/_webfonts.helpers.scss
@function compose-webfont-filename($font-family, $weight, $style) {
    // Font files with 'normal' style don't specify the style in their filenames
    // 'italic', on the other hand, is appended to the filename
    $style: if($style == normal, '', str-capitalise($style));
    // Normal weight is specified as 'Regular' in filenames
    $weight: if($weight == normal, 'Regular', str-capitalise($weight));
    $font: str-remove-white-space($font-family);

    $filename: '#{$font}-#{$weight}#{$style}';

    @return $filename;
}
```
